// dataItem.js
export const menu_list = [
    { menu_name: "Old Good times" },
    { menu_name: "Demand Work" },
    { menu_name: "Demand Work" },
    { menu_name: "Tea" },
    { menu_name: "Once apon a time" },
    { menu_name: "Morning tea" },
    { menu_name: "Cairo" },
    { menu_name: "Drinks" },
    { menu_name: "Fiath Moments" },
    { menu_name: "Bear" },
    { menu_name: "Malindi Beatch" },
    { menu_name: "Out" },
    { menu_name: "Memmories" },
    { menu_name: "Sand birth" },
    { menu_name: "Coast line" },
    { menu_name: "View port" },
    { menu_name: "View port" },
    { menu_name: "Hard times" },
    { menu_name: "Hard times" },
    { menu_name: "Glid" },
    { menu_name: "Lazy mornings" },
    { menu_name: "Lazy mornings" },
    { menu_name: "Pizza" },
    { menu_name: "Morning tea" },
    { menu_name: "Morning tea" },
    { menu_name: "Morning tea" },
    { menu_name: "Morning tea" },
    { menu_name: "Morning tea" },
    { menu_name: "Lunch" },
    { menu_name: "Pizza" },
    { menu_name: "Lunch" },
    { menu_name: "Thoughts" },
    { menu_name: "Thoughts" },
    { menu_name: "Thoughts" },
    { menu_name: "Lazy morning" },
    { menu_name: "Sea board" },
    { menu_name: "Lazy morning" },
    { menu_name: "Sea board" },
    { menu_name: "Thoughts" },
    { menu_name: "Lazy morning" },
    { menu_name: "Lazy morning" },
    { menu_name: "Photo shop" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventure" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" },
    { menu_name: "Adventuresssss" }
  ];
  